<a href="https://colab.research.google.com/github/rcichocki/data-science/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [3]:
np.linalg.norm(v1)

4.123105625617661

In [4]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [5]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [6]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

In [7]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [8]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [9]:
Z.shape

(2, 1)

In [10]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [11]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [12]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [13]:
round(np.linalg.det(A))

10

In [14]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [15]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
A

array([[ 2,  4],
       [-1,  3]])

In [18]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [19]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [21]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [22]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [23]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [25]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [26]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [27]:
X.shape

(2, 1)